server:
  port: 8065

# 存储 DataAgent 业务数据的数据库，并非Agent分析数据的来源
spring:
  datasource:
    url: ${DATA_AGENT_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/saa_data_agent?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_AGENT_DATASOURCE_USERNAME:root}
    password: ${DATA_AGENT_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      separator: ;
      encoding: utf-8
  ai:
    vectorstore:
      type: simple

    mcp:
      server:
        enabled: true
        transport: sse
#        sse-endpoint: /mcp/message
#        sse:
#          path: /mcp/message
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        enabled: true
        options:
          model: qwen-plus
      embedding:
        enabled: true
        options:
          model: text-embedding-v4
    alibaba:
      data-agent:
        llm-service-type: stream
        code-executor:
          # 运行Python代码的环境（生产环境建议使用docker，不建议使用local）
          code-pool-executor: local
        file:
          type: local
          path-prefix: data-agent
          path: ./uploads
          url-prefix: /uploads
          imageSize: 2097152
          oss:
            access-key-id: ${OSS_ACCESS_KEY_ID:}
            access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
            endpoint: ${OSS_ENDPOINT:}
            bucket-name: ${OSS_BUCKET_NAME:}
            custom-domain: ${OSS_CUSTOM_DOMAIN:}
        max-sql-retry-count: 10
        max-sql-optimize-count: 10
        sql-score-threshold: 0.95
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 日志配置
logging:
  level:
    com.alibaba.cloud.ai.mapper: debug
    org.springframework.jdbc: debug
